// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/muzzlefork/first-api/models"
)

// GetHealthOKCode is the HTTP code returned for type GetHealthOK
const GetHealthOKCode int = 200

/*GetHealthOK Successfully returns app information when service is up

swagger:response getHealthOK
*/
type GetHealthOK struct {

	/*
	  In: Body
	*/
	Payload *models.HealthResponse `json:"body,omitempty"`
}

// NewGetHealthOK creates GetHealthOK with default headers values
func NewGetHealthOK() *GetHealthOK {

	return &GetHealthOK{}
}

// WithPayload adds the payload to the get health o k response
func (o *GetHealthOK) WithPayload(payload *models.HealthResponse) *GetHealthOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get health o k response
func (o *GetHealthOK) SetPayload(payload *models.HealthResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHealthOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetHealthUnauthorizedCode is the HTTP code returned for type GetHealthUnauthorized
const GetHealthUnauthorizedCode int = 401

/*GetHealthUnauthorized Unauthorized

swagger:response getHealthUnauthorized
*/
type GetHealthUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.AuthError `json:"body,omitempty"`
}

// NewGetHealthUnauthorized creates GetHealthUnauthorized with default headers values
func NewGetHealthUnauthorized() *GetHealthUnauthorized {

	return &GetHealthUnauthorized{}
}

// WithPayload adds the payload to the get health unauthorized response
func (o *GetHealthUnauthorized) WithPayload(payload *models.AuthError) *GetHealthUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get health unauthorized response
func (o *GetHealthUnauthorized) SetPayload(payload *models.AuthError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHealthUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetHealthForbiddenCode is the HTTP code returned for type GetHealthForbidden
const GetHealthForbiddenCode int = 403

/*GetHealthForbidden Forbidden

swagger:response getHealthForbidden
*/
type GetHealthForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.AuthError `json:"body,omitempty"`
}

// NewGetHealthForbidden creates GetHealthForbidden with default headers values
func NewGetHealthForbidden() *GetHealthForbidden {

	return &GetHealthForbidden{}
}

// WithPayload adds the payload to the get health forbidden response
func (o *GetHealthForbidden) WithPayload(payload *models.AuthError) *GetHealthForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get health forbidden response
func (o *GetHealthForbidden) SetPayload(payload *models.AuthError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHealthForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetHealthInternalServerErrorCode is the HTTP code returned for type GetHealthInternalServerError
const GetHealthInternalServerErrorCode int = 500

/*GetHealthInternalServerError Server Error

swagger:response getHealthInternalServerError
*/
type GetHealthInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetHealthInternalServerError creates GetHealthInternalServerError with default headers values
func NewGetHealthInternalServerError() *GetHealthInternalServerError {

	return &GetHealthInternalServerError{}
}

// WithPayload adds the payload to the get health internal server error response
func (o *GetHealthInternalServerError) WithPayload(payload *models.Error) *GetHealthInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get health internal server error response
func (o *GetHealthInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHealthInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
