// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi trf-microservice-golang-frb
Trip Finalisation Review Bot


    Schemes:
      http
    Host: localhost:8080
    BasePath: /
    Version: {{.Version}}
    License: Copyright Transurban Pty. Ltd. https://www.transurban.com/

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
